#!/bin/bash
###
# Set up environment variables to control building and
# running demonstration mlflow Docker containers
###
echo Setting up environment variables
# mlflow version to install
export MLFLOW_VERSION=1.3.0

# directory to hold mlflow tracking and artifacts
export MLFLOW_TRACKING_DIRECTORY=/Users/zhengmingsong/Desktop/Github/docker-mlflow-postgres-minio/mlflow_server
echo "MLFLOW_TRACKING_DIRECTORY is set to ${MLFLOW_TRACKING_DIRECTORY}"

# mflow tracking server URI
export MLFLOW_TRACKING_HOST=localhost
echo "MLFLOW_TRACKING_HOST is set to ${MLFLOW_TRACKING_HOST}"

export MLFLOW_TRACKING_PORT=5000
echo "MLFLOW_TRACKING_PORT is set to ${MLFLOW_TRACKING_PORT}"

export MLFLOW_TRACKING_URI=http://${MLFLOW_TRACKING_HOST}:${MLFLOW_TRACKING_PORT}
echo "MLFLOW_TRACKING_URI is set to ${MLFLOW_TRACKING_URI}"

# backend tracking store
export MLFLOW_BACKEND_STORE=postgresql://mlflow_user:mlflow_pw@pgdb/mlflow_db
echo "MLFLOW_BACKEND_STORE is set to ${MLFLOW_BACKEND_STORE}"

# backend artifact store
export MINIO_ACCESS_KEY=admin
echo "MINIO_ACCESS_KEY is set to ${MINIO_ACCESS_KEY}"

export MINIO_SECRET_KEY=password
echo "MINIO_SECRET_KEY is set to ${MINIO_SECRET_KEY}"

export MINIO_PORT=9000
echo "MINIO_PORT is set to ${MINIO_PORT}"

export MLFLOW_BUCKET_NAME=mlflow
echo "MLFLOW_BUCKET_NAME is set to ${MLFLOW_BUCKET_NAME}"

export PGADMIN_DEFAULT_EMAIL="mlflow@gmail.com"
echo "PGADMIN_DEFAULT_EMAIL is set to ${PGADMIN_DEFAULT_EMAIL}"

export PGADMIN_DEFAULT_PASSWORD=pgadmin4
echo "PGADMIN_DEFAULT_PASSWORD is set to ${PGADMIN_DEFAULT_PASSWORD}"

